In [1]:
import torch
import torch.nn as nn
from torchMPC.mpc import mpc
from torchMPC.mpc import util
import torch.nn.functional as F
from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np
import pdb

# Cost net (simple running cost and MLP terminal cost)
g = x^2 + u^2


F = xT * MLP(x) * x

In [2]:
class MPCCostNetwork(nn.Module):
    def __init__(self, n_state, n_ctrl):
        super().__init__()
        self.n_state = n_state
        self.n_ctrl = n_ctrl

        # 运行损失 xTQx + uTRu
        self.Q = torch.eye(n_state)
        self.R = torch.eye(n_ctrl)

        # 终端损失网络 xTFx
        # self.terminal_net = nn.Sequential(
        #     nn.Linear(n_state, 128),
        #     nn.ReLU(),
        #     nn.Linear(128, 64),
        #     nn.ReLU(),
        #     nn.Linear(64, n_state * n_state)
        # )

        self.F = nn.Parameter(torch.randn(n_state, n_state))

    def forward(self, tau, terminal=False):
        """
        Args:
            tau: [batch_size, n_state + n_ctrl], concatenated form of state and action
            t: Current timestamp
            T: Total prediction horizon
        Returns:
            cost: [batch_size] 
        """
        batch_size = tau.size(0)
        
        # 分离状态和控制
        # 如果t == T-1，ctrl将会是是零向量，表示不存在，所以不会index out of range
        state = tau[:, :self.n_state]
        ctrl = tau[:, self.n_state:]
        
        # 如果是最后一个时间步，只计算终端损失
        if terminal:
            terminal_F = self.F.repeat(batch_size, 1, 1)
            state = state.unsqueeze(1)
            terminal_cost = torch.bmm(torch.bmm(state, terminal_F), state.transpose(1, 2))
            # pdb.set_trace()
            return terminal_cost.squeeze(-1).squeeze(-1) # Return shape: (batch_size, )
        else:
            return self.running_cost(state, ctrl)
    
    def running_cost(self, state, ctrl): 
        # 简单二次型运行代价
        batch_size = state.shape[0]
        state = state.unsqueeze(1) # (batch_size, 1, n_state)
        ctrl = ctrl.unsqueeze(1)
        Q = self.Q.repeat(batch_size, 1, 1) # (batch_size, n_state, n_state)
        R = self.R.repeat(batch_size, 1, 1)
        xTQx = torch.bmm(torch.bmm(state, Q), state.transpose(1, 2))
        uTRx = torch.bmm(torch.bmm(ctrl, R), ctrl.transpose(1, 2))
        return (xTQx + uTRx).squeeze(-1).squeeze(-1) # Return shape: (batch_size,)

In [3]:
testNet = MPCCostNetwork(3, 2)
tau = torch.randn(10, 5)
cost = testNet(tau)
print(cost)
cost = testNet(tau, terminal=True)
print(cost)

tensor([1.4687, 1.7189, 0.8837, 4.0208, 3.4612, 1.6433, 7.3625, 5.2609, 5.4186,
        7.0082])
tensor([ 0.7363, -0.6830,  0.4612, -0.4283, -1.3558,  1.0301,  1.0114, -1.6508,
        -0.6916,  1.6576], grad_fn=<SqueezeBackward1>)


# Sys Dyna (F = x + u)

In [4]:
class DynamicsF(nn.Module):
    def forward(self, state, action):
        # Dimension of state & action: (batch_size, C)
        assert state.shape[-1] == action.shape[-1]
        return state + action

# Modify the original MPC lib
To support terminal cost.

# Solve optimization problem use MPC

In [5]:
LQR_ITER = 100
batch_size, T, mpc_T = 1, 8, 5
DTYPE = torch.float
nx, nu = 1, 1 # 用1, 1会出问题，最后得到的控制都是nan
n_sc = nx + nu
dynamics = DynamicsF()
cost = MPCCostNetwork(nx, nu)

torch.manual_seed(43)

init_state = torch.tensor([[1.]], dtype=DTYPE)
cost.F = nn.Parameter(torch.tensor([[1.618]], dtype=DTYPE))
u_init = None
x_now = init_state

VN_list = []
x_list = []
u_list = []
for t in range(T):
    ctrl = mpc.MPC(nx, nu, mpc_T, lqr_iter=LQR_ITER, verbose=1,
                exit_unconverged=False, eps=1e-2, n_batch=batch_size, backprop=False, u_init=u_init, 
                grad_method=mpc.GradMethods.AUTO_DIFF)

    x_seq, u_seq, objs = ctrl(x_now, cost, dynamics)
    action = u_seq[0]

    VN_list.append(objs)
    x_list.append(x_now)
    u_list.append(action)

    x_now = dynamics(x_now, action)
    u_init = torch.cat((u_seq[1:], torch.zeros(1, batch_size, nu, dtype=DTYPE)), dim=0)
    # print(x_seq) # Shape: (mpc_T, batch_size, nx)
    # print(u_seq) # Shape: (mpc_T, batch_size, nu)
    # print(objs)  # Shape: (batch_size,)
    # Verbose > 0时，打印出来的log数据分别表示：
    # iLQR迭代次数、最优轨迹的平均代价、action更新的最大范数(表示action的变化量)、线搜索步长均值、QP子问题的总迭代次数

print(VN_list)
print(x_list)
print(u_list)

Initial mean(cost): 5.6180e+00
| iter | mean(cost) | ||full_du||_max | mean(alphas) | total_qp_iters |
| 0 | 1.6180e+00 | 6.69e-01 | 1.00e+00 | tensor([0.]) |
| 1 | 1.6180e+00 | 6.51e-08 | 1.00e+00 | tensor([0.]) |
Initial mean(cost): 2.3652e-01
| 0 | 2.3607e-01 | 1.32e-02 | 1.00e+00 | tensor([0.], grad_fn=<LQRStepFnBackward>) |
| 1 | 2.3607e-01 | 9.31e-10 | 1.00e+00 | tensor([0.], grad_fn=<LQRStepFnBackward>) |
Initial mean(cost): 3.4508e-02
| 0 | 3.4442e-02 | 5.02e-03 | 1.00e+00 | tensor([0.], grad_fn=<LQRStepFnBackward>) |
Initial mean(cost): 5.0346e-03
| 0 | 5.0250e-03 | 1.92e-03 | 1.00e+00 | tensor([0.], grad_fn=<LQRStepFnBackward>) |
Initial mean(cost): 7.3454e-04
| 0 | 7.3314e-04 | 7.33e-04 | 1.00e+00 | tensor([0.], grad_fn=<LQRStepFnBackward>) |
Initial mean(cost): 1.0717e-04
| 0 | 1.0696e-04 | 2.80e-04 | 1.00e+00 | tensor([0.], grad_fn=<LQRStepFnBackward>) |
Initial mean(cost): 1.5636e-05
| 0 | 1.5606e-05 | 1.07e-04 | 1.00e+00 | tensor([0.], grad_fn=<LQRStepFnBackward>) |
Init

# Verify the RDP inequality

In [6]:
def cal_RDP_criteria(VN_list, x_list, u_list, alpha, MPC_T, func, eps, test=False):
    """
    Input:
        VN_list: list of the cost function value
        x_list: list of the state
        u_list: list of the control
        cost_nn: the cost function
        alpha: the weight of the running cost term
        func: the function used to incoporate the RDP inequality into the loss function
        test: whether to print the RDP value
    Return:
        RDP criteria
    """
    loss = 0
    for i in range(MPC_T - 1):
        tau = torch.cat((x_list[i], u_list[i]), dim=1)
        RDP = (VN_list[i+1] + alpha * cost(tau, False)) - VN_list[i] - eps # Wish RDP <= 0
        if test:
            print(f'RDP{i}: {RDP}')
        loss += func(RDP)
    return loss

In [7]:
# 测测上面的小例子
alpha = 1
loss = cal_RDP_criteria(VN_list, x_list, u_list, alpha, T, lambda x: torch.relu(x), 1e-7, test=True)
print(loss)

RDP0: tensor([-1.0000e-07], grad_fn=<SubBackward0>)
RDP1: tensor([-1.0000e-07], grad_fn=<SubBackward0>)
RDP2: tensor([-1.0000e-07], grad_fn=<SubBackward0>)
RDP3: tensor([-1.0047e-07], grad_fn=<SubBackward0>)
RDP4: tensor([-1.0000e-07], grad_fn=<SubBackward0>)
RDP5: tensor([-1.0000e-07], grad_fn=<SubBackward0>)
RDP6: tensor([-1.0000e-07], grad_fn=<SubBackward0>)
tensor([0.], grad_fn=<AddBackward0>)


# Large scale test

In [8]:
def myLogger(date, msg, *args):
    try:
        # 把data和args拼接成一个字符串
        log_name = f"{date}_" + "_".join(map(str, args)) + ".txt"
        with open('./testLog/' + log_name, 'a') as file:
            file.write(msg + "\n")
    except IOError as e:
        print(f"写入文件失败: {e}")

In [9]:
def solve_mpc(nx, nu, batch_size, mpc_T, ocp_T, lqr_iter, dynamics, cost, DTYPE):
    u_init = None
    x_init = torch.randn(batch_size, nx, dtype=DTYPE) * 100
    
    x_list = []
    u_list = []
    VN_list = []
    
    x_now = x_init
    for i in range(mpc_T):
        ctrl = mpc.MPC(nx, nu, ocp_T, lqr_iter=LQR_ITER, verbose=0,
                    exit_unconverged=False, eps=1e-2, n_batch=batch_size, backprop=True, u_init=u_init, 
                    grad_method=mpc.GradMethods.AUTO_DIFF)
        
        x_seq, u_seq, objs = ctrl(x_now, cost, dynamics)
        action = u_seq[0]

        VN_list.append(objs)
        x_list.append(x_now)
        u_list.append(action)

        x_now = dynamics(x_now, action)
        u_init = torch.cat((u_seq[1:], torch.zeros(1, batch_size, nu, dtype=DTYPE)), dim=0)
    return x_list, u_list, VN_list

In [10]:
from torchMPC.mpc.dynamics import AffineDynamics
from torch.optim import Adam

In [ ]:
DTYPES = torch.float32
torch.set_default_dtype(DTYPES)
nx, nu = 1, 1
n_sc = nx + nu
batch_size, mpc_T, ocp_T = 20, 10, 5
LQR_ITER = 100

loss_eps = 1e-8
rdp_eps = 1e-12

A = torch.eye(nx, dtype=DTYPES)
B = torch.eye(nu, dtype=DTYPES)
dynamics = AffineDynamics(A, B)

cost = MPCCostNetwork(nx, nu)
cost.F = nn.Parameter(torch.tensor([[1.4]], dtype=DTYPES))

optimizer = Adam(cost.parameters(), lr=1e-3)

n_epoch = 1000

terminal_param_list = []

loss = 0
for epoch in tqdm(range(n_epoch)):
    x_list, u_list, VN_list = solve_mpc(nx, nu, batch_size, mpc_T, ocp_T, LQR_ITER, dynamics, cost, DTYPES)

    terminal_param_list.append(cost.F.item())
    
    optimizer.zero_grad()
    loss = cal_RDP_criteria(VN_list, x_list, u_list, 1, mpc_T, lambda x: torch.relu(x), rdp_eps, test=False).mean()
    RDP_points = cal_RDP_criteria(VN_list, x_list, u_list, 1, mpc_T, lambda x: torch.sign(x), rdp_eps, test=False).sum()
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0 or loss.item() < loss_eps:
        msg = f'Epoch: {epoch}, Loss: {loss}, RDP Points: {RDP_points}' + '\n' + f'Terminal cost {cost.F.item()}'
        myLogger("250329", msg, n_epoch, batch_size, mpc_T, ocp_T, loss_eps)
        if loss.item() < loss_eps:
            break

msg = f'Final Epoch: {epoch}, Loss: {loss}, RDP Points: {RDP_points}' + '\n' + f'Finished with terminal cost {cost.F.item()}'
myLogger("250329", msg, n_epoch, batch_size, mpc_T, ocp_T, loss_eps)

print(cost.F)

In [ ]:
plt.plot(terminal_param_list)

# Hyperparameter test

In [11]:
def hyperLogger(dir, msg, filename):
    try:
        # 把data和args拼接成一个字符串
        with open(dir + filename + '.txt', 'a') as file:
            file.write(msg + "\n")
    except IOError as e:
        print(f"写入文件失败: {e}")

In [12]:
def test_hyper(hyper_dict, test_name, save_path='./'):
    date = hyper_dict['date']
    filename = date + test_name + str(hyper_dict[test_name])

    DTYPES = torch.float32
    torch.set_default_dtype(DTYPES)
    nx, nu = hyper_dict['nx'], hyper_dict['nu']
    n_sc = nx + nu
    batch_size, mpc_T, ocp_T = hyper_dict['batch_size'], hyper_dict['mpc_T'], hyper_dict['ocp_T']
    LQR_ITER = hyper_dict['LQR_ITER']

    loss_eps = hyper_dict['loss_eps']
    rdp_eps = hyper_dict['rdp_eps']

    A = torch.eye(nx, dtype=DTYPES)
    B = torch.eye(nu, dtype=DTYPES)
    dynamics = AffineDynamics(A, B)

    cost = MPCCostNetwork(nx, nu)
    cost.F = nn.Parameter(torch.tensor([[hyper_dict['init_F']]], dtype=DTYPES))

    optimizer = Adam(cost.parameters(), lr=hyper_dict['lr'])

    n_epoch = hyper_dict['n_epoch']

    terminal_param_list = []

    loss = 0
    for epoch in tqdm(range(n_epoch)):
        x_list, u_list, VN_list = solve_mpc(nx, nu, batch_size, mpc_T, ocp_T, LQR_ITER, dynamics, cost, DTYPES)

        terminal_param_list.append(cost.F.item())
        
        optimizer.zero_grad()
        loss = cal_RDP_criteria(VN_list, x_list, u_list, 1, mpc_T, lambda x: torch.relu(x), rdp_eps, test=False).mean()
        RDP_points = cal_RDP_criteria(VN_list, x_list, u_list, 1, mpc_T, lambda x: torch.sign(x), rdp_eps, test=False).sum()
        loss.backward()
        optimizer.step()

        if epoch % 50 == 0 or loss.item() < loss_eps:
            msg = f'Epoch: {epoch}, Loss: {loss}, RDP Points: {RDP_points}' + '\n' + f'Terminal cost: {cost.F.item()}'
            hyperLogger(save_path, msg, filename)
            if loss.item() < loss_eps:
                break

    msg = f'Final Epoch: {epoch}, Loss: {loss}, RDP Points: {RDP_points}' + '\n' + f'Finished with terminal cost {cost.F.item()}'
    hyperLogger(save_path, msg, filename)

    # draw the terminal cost parameter and save the figure
    plt.plot(terminal_param_list)
    plt.xlabel('Epoch')
    plt.ylabel('Terminal Cost Parameter')
    plt.title('Terminal Cost Parameter vs Epoch')
    plt.grid()
    plt.savefig(save_path + f'{filename}.png')
    plt.close()

    # Use trained cost to test the performance
    x_list, u_list, VN_list = solve_mpc(nx, nu, 1, mpc_T, ocp_T, LQR_ITER, dynamics, cost, DTYPES)
    # draw the trajectories and save the figure (only one batch)
    x_plot = [x.item() for x in x_list]
    u_plot = [u.item() for u in u_list]
    VN_list = [np.sqrt(v.item()) for v in VN_list]
    plt.plot(x_plot, label='State')
    plt.plot(u_plot, label='Control')
    plt.plot(VN_list, label='Cost (sqrt)')
    plt.xlabel('Time Step')
    plt.ylabel('Value')
    plt.legend()
    plt.title('Trajectories')
    plt.grid()
    plt.savefig(save_path + f'{filename}_trajectories.png')
    plt.close()

In [13]:
def generate_test_hyper_dict(date, test_name, nx, nu, batch_size, mpc_T, ocp_T, LQR_ITER, loss_eps, rdp_eps, init_F, lr, n_epoch):
    hyper_dict = {
        'date': date,
        'test_name': test_name,
        'nx': nx,
        'nu': nu,
        'batch_size': batch_size,
        'mpc_T': mpc_T,
        'ocp_T': ocp_T,
        'LQR_ITER': LQR_ITER,
        'loss_eps': loss_eps,
        'rdp_eps': rdp_eps,
        'init_F': init_F,
        'lr': lr,
        'n_epoch': n_epoch
    }
    return hyper_dict

test_hyper_dict = generate_test_hyper_dict(
    date='250330',
    test_name='test_1',
    nx=1,
    nu=1,
    batch_size=1,
    mpc_T=10,
    ocp_T=5,
    LQR_ITER=100,
    loss_eps=1e-8,
    rdp_eps=0.0,
    init_F=1.4,
    lr=0.001,
    n_epoch=1000
)

# test_hyper(test_hyper_dict, 'ocp_T', save_path='./testLog/')

## Test mpcT

In [ ]:
for i in range(12, 1, -1):
    test_hyper_dict = generate_test_hyper_dict(
        date='250330',
        test_name='test_2',
        nx=1,
        nu=1,
        batch_size=30,
        mpc_T=i,
        ocp_T=2,
        LQR_ITER=100,
        loss_eps=1e-8,
        rdp_eps=0.0,
        init_F=1.4,
        lr=0.001,
        n_epoch=1000
    )
    test_hyper(test_hyper_dict, 'mpc_T', save_path='./testLog/mpcT/')

# Test ocpT

In [14]:
for i in range(11, 13):
    test_hyper_dict = generate_test_hyper_dict(
        date='250330',
        test_name='test_3',
        nx=1,
        nu=1,
        batch_size=30,
        mpc_T=10,
        ocp_T=i,
        LQR_ITER=100,
        loss_eps=1e-8,
        rdp_eps=0.0,
        init_F=1.4,
        lr=0.001,
        n_epoch=1000
    )
    test_hyper(test_hyper_dict, 'ocp_T', save_path='./testLog/ocpT/')

100%|██████████| 1000/1000 [10:14<00:00,  1.63it/s]


# Test RDP_eps

In [16]:
for i in range(3, 12):
    eps = 10 ** -i
    if i == 11:
        eps = 0

    test_hyper_dict = generate_test_hyper_dict(
        date='250330',
        test_name='test_4',
        nx=1,
        nu=1,
        batch_size=30,
        mpc_T=10,
        ocp_T=3,
        LQR_ITER=100,
        loss_eps=1e-8,
        rdp_eps=eps,
        init_F=1.4,
        lr=0.001,
        n_epoch=1000
    )
    test_hyper(test_hyper_dict, 'rdp_eps', save_path='./testLog/RDP_eps/')

100%|██████████| 1000/1000 [04:20<00:00,  3.84it/s]
